// Generated by skein-codegen from scalars 1. Do not edit.


/// The family has no adjustable bounds.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Limits {
}

/// The schema's maximum limits.
pub const CEILINGS: Limits = Limits {
};

/// A field or tag that caused a codec problem.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Path {
    /// The tag of Flag.
    FlagTag,
    /// The a field of Scalars.
    ScalarsA,
    /// The b field of Scalars.
    ScalarsB,
    /// The c field of Scalars.
    ScalarsC,
    /// The d field of Scalars.
    ScalarsD,
    /// The e field of Scalars.
    ScalarsE,
    /// The f field of Scalars.
    ScalarsF,
    /// The g field of Scalars.
    ScalarsG,
    /// The h field of Scalars.
    ScalarsH,
    /// Bytes after Scalars.
    ScalarsTail,
}

/// A decoding or bound failure at a schema path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Problem {
    pub path: Path,
    pub reason: skein_codec::Reason,
}

/// Flag in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Flag {
    /// off without a payload.
    Off,
    /// on without a payload.
    On,
}

impl Flag {
    /// Accepts a variant; this family has no adjustable bounds.
    #[must_use]
    pub fn new(_limits: &Limits, value: Self) -> Self { value }
}

/// Movable fields of Scalars.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ScalarsParts {
    /// The a field.
    pub a: u8,
    /// The b field.
    pub b: u16,
    /// The c field.
    pub c: u32,
    /// The d field.
    pub d: u64,
    /// The e field.
    pub e: bool,
    /// The f field.
    pub f: skein_lib::Duration,
    /// The g field.
    pub g: [u8; 2],
    /// The h field.
    pub h: Flag,
}

/// Scalars in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Scalars {
    a: u8,
    b: u16,
    c: u32,
    d: u64,
    e: bool,
    f: skein_lib::Duration,
    g: [u8; 2],
    h: Flag,
}

impl Scalars {
    /// Makes a value; this family has no adjustable bounds.
    #[must_use]
    pub fn new(_limits: &Limits, parts: ScalarsParts) -> Self {
        let ScalarsParts { a, b, c, d, e, f, g, h } = parts;
        Self { a, b, c, d, e, f, g, h }
    }

    /// Reads the a field.
    #[must_use]
    pub fn a(&self) -> u8 { self.a }

    /// Reads the b field.
    #[must_use]
    pub fn b(&self) -> u16 { self.b }

    /// Reads the c field.
    #[must_use]
    pub fn c(&self) -> u32 { self.c }

    /// Reads the d field.
    #[must_use]
    pub fn d(&self) -> u64 { self.d }

    /// Reads the e field.
    #[must_use]
    pub fn e(&self) -> bool { self.e }

    /// Reads the f field.
    #[must_use]
    pub fn f(&self) -> skein_lib::Duration { self.f }

    /// Reads the g field.
    #[must_use]
    pub fn g(&self) -> &[u8; 2] { &self.g }

    /// Reads the h field.
    #[must_use]
    pub fn h(&self) -> &Flag { &self.h }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> ScalarsParts { ScalarsParts { a: self.a, b: self.b, c: self.c, d: self.d, e: self.e, f: self.f, g: self.g, h: self.h } }

}

impl Flag {
    /// Measures this variant's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        match self {
            Self::Off | Self::On => 1,
        }
    }

    /// Writes this variant's tag and payload.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        match self {
            Self::Off => writer.put(&[0_u8])?,
            Self::On => writer.put(&[1_u8])?,
        }
        Ok(())
    }

    /// Reads a whole variant and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let tag = reader.u8().ok_or(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Short })?;
        let value = match tag {
            0 => Self::Off,
            1 => Self::On,
            _ => return Err(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Tag }),
        };
        Ok(Self::new(limits, value))
    }
}

impl Scalars {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(2).expect("schema ceilings fit u32");
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size = size.checked_add(8).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(8).expect("schema ceilings fit u32");
        size = size.checked_add(2).expect("schema ceilings fit u32");
        let field_h = &self.h;
        size = size.checked_add(field_h.measure()).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_a = &self.a;
        writer.put(&[*field_a])?;
        let field_b = &self.b;
        writer.put(&field_b.to_be_bytes())?;
        let field_c = &self.c;
        writer.put(&field_c.to_be_bytes())?;
        let field_d = &self.d;
        writer.put(&field_d.to_be_bytes())?;
        let field_e = &self.e;
        writer.put(&[u8::from(*field_e)])?;
        let field_f = &self.f;
        writer.put(&field_f.as_nanos().to_be_bytes())?;
        let field_g = &self.g;
        writer.put(field_g)?;
        let field_h = &self.h;
        field_h.encode(writer)?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::ScalarsTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_a = reader.u8().ok_or(Problem { path: Path::ScalarsA, reason: skein_codec::Reason::Short })?;
        let decoded_b = reader.u16().ok_or(Problem { path: Path::ScalarsB, reason: skein_codec::Reason::Short })?;
        let decoded_c = reader.u32().ok_or(Problem { path: Path::ScalarsC, reason: skein_codec::Reason::Short })?;
        let decoded_d = reader.u64().ok_or(Problem { path: Path::ScalarsD, reason: skein_codec::Reason::Short })?;
        let decoded_e = match reader.u8().ok_or(Problem { path: Path::ScalarsE, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::ScalarsE, reason: skein_codec::Reason::Bool }) };
        let decoded_f = skein_lib::Duration::from_nanos(reader.u64().ok_or(Problem { path: Path::ScalarsF, reason: skein_codec::Reason::Short })?);
        let decoded_g = { let bytes = reader.bytes(2).ok_or(Problem { path: Path::ScalarsG, reason: skein_codec::Reason::Short })?; bytes.try_into().expect("fixed length checked") };
        let decoded_h = Flag::decode_from(limits, reader)?;
        Ok(Self::new(limits, ScalarsParts { a: decoded_a, b: decoded_b, c: decoded_c, d: decoded_d, e: decoded_e, f: decoded_f, g: decoded_g, h: decoded_h }))
    }
}

