// Generated by skein-codegen from scalars 1. Do not edit.


/// The family has no adjustable bounds.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Limits {
}

/// The schema's maximum limits.
pub const CEILINGS: Limits = Limits {
};

/// A field or tag that caused a codec problem.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Path {
    /// Bytes after Empty.
    EmptyTail,
    /// The tag of Flag.
    FlagTag,
    /// The a field of Scalars.
    ScalarsA,
    /// The b field of Scalars.
    ScalarsB,
    /// The c field of Scalars.
    ScalarsC,
    /// The d field of Scalars.
    ScalarsD,
    /// The e field of Scalars.
    ScalarsE,
    /// The f field of Scalars.
    ScalarsF,
    /// The g field of Scalars.
    ScalarsG,
    /// The h field of Scalars.
    ScalarsH,
    /// Bytes after Scalars.
    ScalarsTail,
}

/// A decoding or bound failure at a schema path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Problem {
    pub path: Path,
    pub reason: skein_codec::Reason,
}

/// Movable fields of Empty.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct EmptyParts {
}

/// Empty in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Empty {
}

impl Empty {
    /// Makes a value; this family has no adjustable bounds.
    #[must_use]
    pub fn new(_limits: &Limits, parts: EmptyParts) -> Self {
        let EmptyParts {  } = parts;
        Self {  }
    }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> EmptyParts { EmptyParts {  } }

}

/// Flag in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Flag {
    /// off without a payload.
    Off,
    /// on without a payload.
    On,
}

impl Flag {
    /// Accepts a variant; this family has no adjustable bounds.
    #[must_use]
    pub fn new(_limits: &Limits, value: Self) -> Self { value }
}

/// Movable fields of Scalars.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ScalarsParts {
    /// The a field.
    pub a: u8,
    /// The b field.
    pub b: u16,
    /// The c field.
    pub c: u32,
    /// The d field.
    pub d: u64,
    /// The e field.
    pub e: bool,
    /// The f field.
    pub f: skein_lib::Duration,
    /// The g field.
    pub g: [u8; 2],
    /// The h field.
    pub h: Flag,
}

/// Scalars in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Scalars {
    a: u8,
    b: u16,
    c: u32,
    d: u64,
    e: bool,
    f: skein_lib::Duration,
    g: [u8; 2],
    h: Flag,
}

impl Scalars {
    /// Makes a value; this family has no adjustable bounds.
    #[must_use]
    pub fn new(_limits: &Limits, parts: ScalarsParts) -> Self {
        let ScalarsParts { a, b, c, d, e, f, g, h } = parts;
        Self { a, b, c, d, e, f, g, h }
    }

    /// Reads the a field.
    #[must_use]
    pub fn a(&self) -> u8 { self.a }

    /// Reads the b field.
    #[must_use]
    pub fn b(&self) -> u16 { self.b }

    /// Reads the c field.
    #[must_use]
    pub fn c(&self) -> u32 { self.c }

    /// Reads the d field.
    #[must_use]
    pub fn d(&self) -> u64 { self.d }

    /// Reads the e field.
    #[must_use]
    pub fn e(&self) -> bool { self.e }

    /// Reads the f field.
    #[must_use]
    pub fn f(&self) -> skein_lib::Duration { self.f }

    /// Reads the g field.
    #[must_use]
    pub fn g(&self) -> &[u8; 2] { &self.g }

    /// Reads the h field.
    #[must_use]
    pub fn h(&self) -> &Flag { &self.h }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> ScalarsParts { ScalarsParts { a: self.a, b: self.b, c: self.c, d: self.d, e: self.e, f: self.f, g: self.g, h: self.h } }

}

impl Empty {
    /// Measures this empty record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 { 0_u32 }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        writer.put(&[])
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader);
        if !reader.is_empty() { return Err(Problem { path: Path::EmptyTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, _reader: &mut skein_lib::Reader<'_>) -> Self {
        Self::new(limits, EmptyParts {})
    }
}

impl Flag {
    /// Measures this variant's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        match self {
            Self::Off | Self::On => 1,
        }
    }

    /// Writes this variant's tag and payload.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        match self {
            Self::Off => writer.put(&[0_u8])?,
            Self::On => writer.put(&[1_u8])?,
        }
        Ok(())
    }

    /// Reads a whole variant and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let tag = reader.u8().ok_or(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Short })?;
        let value = match tag {
            0 => Self::Off,
            1 => Self::On,
            _ => return Err(Problem { path: Path::FlagTag, reason: skein_codec::Reason::Tag }),
        };
        Ok(Self::new(limits, value))
    }
}

impl Scalars {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(2).expect("schema ceilings fit u32");
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size = size.checked_add(8).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(8).expect("schema ceilings fit u32");
        size = size.checked_add(2).expect("schema ceilings fit u32");
        let field_h = &self.h;
        size = size.checked_add(field_h.measure()).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_a = &self.a;
        writer.put(&[*field_a])?;
        let field_b = &self.b;
        writer.put(&field_b.to_be_bytes())?;
        let field_c = &self.c;
        writer.put(&field_c.to_be_bytes())?;
        let field_d = &self.d;
        writer.put(&field_d.to_be_bytes())?;
        let field_e = &self.e;
        writer.put(&[u8::from(*field_e)])?;
        let field_f = &self.f;
        writer.put(&field_f.as_nanos().to_be_bytes())?;
        let field_g = &self.g;
        writer.put(field_g)?;
        let field_h = &self.h;
        field_h.encode(writer)?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::ScalarsTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_a = reader.u8().ok_or(Problem { path: Path::ScalarsA, reason: skein_codec::Reason::Short })?;
        let decoded_b = reader.u16().ok_or(Problem { path: Path::ScalarsB, reason: skein_codec::Reason::Short })?;
        let decoded_c = reader.u32().ok_or(Problem { path: Path::ScalarsC, reason: skein_codec::Reason::Short })?;
        let decoded_d = reader.u64().ok_or(Problem { path: Path::ScalarsD, reason: skein_codec::Reason::Short })?;
        let decoded_e = match reader.u8().ok_or(Problem { path: Path::ScalarsE, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::ScalarsE, reason: skein_codec::Reason::Bool }) };
        let decoded_f = skein_lib::Duration::from_nanos(reader.u64().ok_or(Problem { path: Path::ScalarsF, reason: skein_codec::Reason::Short })?);
        let decoded_g = { let bytes = reader.bytes(2).ok_or(Problem { path: Path::ScalarsG, reason: skein_codec::Reason::Short })?; bytes.try_into().expect("fixed length checked") };
        let decoded_h = Flag::decode_from(limits, reader)?;
        Ok(Self::new(limits, ScalarsParts { a: decoded_a, b: decoded_b, c: decoded_c, d: decoded_d, e: decoded_e, f: decoded_f, g: decoded_g, h: decoded_h }))
    }
}

fn limits_valid(_limits: &Limits) -> bool { true }

impl Empty {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let size = 0_u64;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let heap = 0_u64;
        Some(heap)
    }
}

impl Flag {
    /// Maximum encoded bytes among variants.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let biggest = 0_u64;
        1_u64.checked_add(biggest)
    }

    /// Maximum heap held by any decoded variant.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let biggest = 0_u64;
        Some(biggest)
    }
}

impl Scalars {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(2_u64)?;
        size = size.checked_add(4_u64)?;
        size = size.checked_add(8_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(8_u64)?;
        size = size.checked_add(u64::from(2_u32))?;
        size = size.checked_add(Flag::worst_case_bytes(limits)?)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(Flag::worst_case_heap(limits)?)?;
        Some(heap)
    }
}

/// Maximum wire bytes among this family's top-level types.
#[must_use]
pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(Empty::worst_case_bytes(limits)?);
    biggest = biggest.max(Flag::worst_case_bytes(limits)?);
    biggest = biggest.max(Scalars::worst_case_bytes(limits)?);
    Some(biggest)
}

/// Maximum heap held by one decoded top-level value.
#[must_use]
pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(Empty::worst_case_heap(limits)?);
    biggest = biggest.max(Flag::worst_case_heap(limits)?);
    biggest = biggest.max(Scalars::worst_case_heap(limits)?);
    Some(biggest)
}

#[cfg(test)]
mod golden_tests {
    use super::{CEILINGS, Empty, EmptyParts, Flag, Scalars, ScalarsParts};

    #[test]
    fn record_empty_smallest() {
        let value = Empty::new(&CEILINGS, EmptyParts {  });
        let golden: &[u8] = &[];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Empty::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_empty_full() {
        let value = Empty::new(&CEILINGS, EmptyParts {  });
        let golden: &[u8] = &[];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Empty::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_flag_off_smallest() {
        let value = Flag::Off;
        let golden: &[u8] = &[0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Flag::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_flag_off_full() {
        let value = Flag::Off;
        let golden: &[u8] = &[0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Flag::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_flag_on_smallest() {
        let value = Flag::On;
        let golden: &[u8] = &[1];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Flag::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_flag_on_full() {
        let value = Flag::On;
        let golden: &[u8] = &[1];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Flag::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_scalars_smallest() {
        let value = Scalars::new(&CEILINGS, ScalarsParts { a: 0_u8, b: 0_u16, c: 0_u32, d: 0_u64, e: false, f: skein_lib::Duration::from_nanos(0_u64), g: [0_u8; 2], h: Flag::Off });
        let golden: &[u8] = &[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Scalars::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_scalars_full() {
        let value = Scalars::new(&CEILINGS, ScalarsParts { a: u8::MAX, b: u16::MAX, c: u32::MAX, d: u64::MAX, e: true, f: skein_lib::Duration::from_nanos(u64::MAX), g: [165_u8; 2], h: Flag::Off });
        let golden: &[u8] = &[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 1, 255, 255, 255, 255, 255, 255, 255, 255, 165, 165, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Scalars::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

}
