//! A schema parser and generator for bounded codecs (codec.md, sections 3-6).
//! The schema and declaration tree are author-owned; this crate has no peer
//! input or running machine state. [`parse`] validates a schema before code
//! generation.

extern crate alloc;

mod check;
mod emit_codec;
mod emit_limits;
mod emit_types;
mod parse;

pub use parse::{Error, parse};

/// One schema version of a family.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Schema {
    pub family: String,
    pub version: u16,
    pub declarations: Vec<Declaration>,
}

/// A record or enumeration in declaration order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Declaration {
    Record(Record),
    Enum(Enumeration),
}

/// An ordered group of fields, optionally with a version prefix.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Record {
    pub line: usize,
    pub name: String,
    pub versioned: bool,
    pub fields: Vec<Field>,
}

/// An ordered group of variants, each holding at most one earlier record.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Enumeration {
    pub line: usize,
    pub name: String,
    pub variants: Vec<Variant>,
}

/// A named field of a record.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Field {
    pub line: usize,
    pub name: String,
    pub ty: Type,
}

/// A named variant with an optional record payload.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Variant {
    pub line: usize,
    pub name: String,
    pub record: Option<String>,
}

/// A field's bounded wire type.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Type {
    U8,
    U16,
    U32,
    U64,
    Bool,
    Duration,
    Fixed(u32),
    Bytes(u32),
    Text(u32),
    List(u32, Box<Type>),
    Option(Box<Type>),
    Named(String),
}

/// Generated Rust for one schema version.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Output {
    pub rust: String,
}

fn uses_box(ty: &Type) -> bool {
    match ty {
        Type::Bytes(_) | Type::Text(_) => true,
        Type::List(_, item) | Type::Option(item) => uses_box(item),
        Type::U8
        | Type::U16
        | Type::U32
        | Type::U64
        | Type::Bool
        | Type::Duration
        | Type::Fixed(_)
        | Type::Named(_) => false,
    }
}

fn uses_list(ty: &Type) -> bool {
    match ty {
        Type::List(_, _) => true,
        Type::Option(item) => uses_list(item),
        Type::U8
        | Type::U16
        | Type::U32
        | Type::U64
        | Type::Bool
        | Type::Duration
        | Type::Fixed(_)
        | Type::Bytes(_)
        | Type::Text(_)
        | Type::Named(_) => false,
    }
}

/// Writes plain Rust types and limits from a validated schema.
#[must_use]
pub fn generate(schema: &Schema) -> Output {
    let mut rust = format!("// Generated by skein-codegen from {} {}. Do not edit.\n\n", schema.family, schema.version);
    let fields = schema
        .declarations
        .iter()
        .filter_map(|declaration| match declaration {
            Declaration::Record(record) => Some(record.fields.as_slice()),
            Declaration::Enum(_) => None,
        })
        .flatten();
    let types = fields.map(|field| &field.ty).collect::<Vec<_>>();
    if types.iter().any(|ty| uses_box(ty)) {
        rust.push_str("use alloc::boxed::Box;\n");
    }
    if types.iter().any(|ty| uses_list(ty)) {
        rust.push_str("use skein_lib::List;\n");
    }
    rust.push('\n');
    emit_limits::emit(schema, &mut rust);
    emit_types::emit(schema, &mut rust);
    emit_codec::emit(schema, &mut rust);
    Output { rust }
}
