// Generated by skein-codegen from lint-fixture 1. Do not edit.

use alloc::boxed::Box;
use skein_lib::List;

/// The family's adjustable limits, each no larger than its ceiling.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Limits {
    pub host_tool_payload: u32,
    pub payload_data: u32,
    pub one_byte_items_items: u32,
}

/// The schema's maximum limits.
pub const CEILINGS: Limits = Limits {
    host_tool_payload: 10_000,
    payload_data: 4,
    one_byte_items_items: 4,
};

/// A field or tag that caused a codec problem.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Path {
    /// The `inspect` field of `HostTool`.
    HostToolInspect,
    /// The `modify` field of `HostTool`.
    HostToolModify,
    /// The `shell` field of `HostTool`.
    HostToolShell,
    /// The `agents` field of `HostTool`.
    HostToolAgents,
    /// The `max_tokens` field of `HostTool`.
    HostToolMaxTokens,
    /// The `payload` field of `HostTool`.
    HostToolPayload,
    /// Bytes after `HostTool`.
    HostToolTail,
    /// The `count` field of `Boundless`.
    BoundlessCount,
    /// Bytes after `Boundless`.
    BoundlessTail,
    /// The `data` field of `Payload`.
    PayloadData,
    /// Bytes after `Payload`.
    PayloadTail,
    /// The `value` field of `OtherPayload`.
    OtherPayloadValue,
    /// Bytes after `OtherPayload`.
    OtherPayloadTail,
    /// The tag of `Shared`.
    SharedTag,
    /// The `items` field of `OneByteItems`.
    OneByteItemsItems,
    /// Bytes after `OneByteItems`.
    OneByteItemsTail,
}

/// A decoding or bound failure at a schema path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Problem {
    pub path: Path,
    pub reason: skein_codec::Reason,
}

/// Movable fields of `HostTool`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct HostToolParts {
    /// Boolean fields in schema order.
    pub skein_bools: [bool; 4],
    /// The `max_tokens` field.
    pub max_tokens: u32,
    /// The `payload` field.
    pub payload: Box<[u8]>,
}

/// `HostTool` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct HostTool {
    skein_bools: [bool; 4],
    max_tokens: u32,
    payload: Box<[u8]>,
}

impl HostTool {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: HostToolParts) -> Result<Self, Problem> {
        let HostToolParts { skein_bools, max_tokens, payload } = parts;
        let value = Self { skein_bools, max_tokens, payload };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `inspect` field.
    #[must_use]
    pub fn inspect(&self) -> bool { { let [value, _, _, _] = self.skein_bools; value } }

    /// Reads the `modify` field.
    #[must_use]
    pub fn modify(&self) -> bool { { let [_, value, _, _] = self.skein_bools; value } }

    /// Reads the `shell` field.
    #[must_use]
    pub fn shell(&self) -> bool { { let [_, _, value, _] = self.skein_bools; value } }

    /// Reads the `agents` field.
    #[must_use]
    pub fn agents(&self) -> bool { { let [_, _, _, value] = self.skein_bools; value } }

    /// Reads the `max_tokens` field.
    #[must_use]
    pub fn max_tokens(&self) -> u32 { self.max_tokens }

    /// Reads the `payload` field.
    #[must_use]
    pub fn payload(&self) -> &[u8] { &self.payload }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> HostToolParts { HostToolParts { skein_bools: self.skein_bools, max_tokens: self.max_tokens, payload: self.payload } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        if self.payload.len() > usize::try_from(limits.host_tool_payload.min(CEILINGS.host_tool_payload)).expect("u32 fits usize") { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// Movable fields of `Boundless`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct BoundlessParts {
    /// The `count` field.
    pub count: u32,
}

/// `Boundless` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Boundless {
    count: u32,
}

impl Boundless {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: BoundlessParts) -> Result<Self, Problem> {
        let BoundlessParts { count } = parts;
        let value = Self { count };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `count` field.
    #[must_use]
    pub fn count(&self) -> u32 { self.count }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> BoundlessParts { BoundlessParts { count: self.count } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        let Self { .. } = self;
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// Movable fields of `Payload`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct PayloadParts {
    /// The `data` field.
    pub data: Box<[u8]>,
}

/// `Payload` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Payload {
    data: Box<[u8]>,
}

impl Payload {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: PayloadParts) -> Result<Self, Problem> {
        let PayloadParts { data } = parts;
        let value = Self { data };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `data` field.
    #[must_use]
    pub fn data(&self) -> &[u8] { &self.data }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> PayloadParts { PayloadParts { data: self.data } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        if self.data.len() > usize::try_from(limits.payload_data.min(CEILINGS.payload_data)).expect("u32 fits usize") { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// Movable fields of `OtherPayload`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct OtherPayloadParts {
    /// The `value` field.
    pub value: u8,
}

/// `OtherPayload` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct OtherPayload {
    value: u8,
}

impl OtherPayload {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: OtherPayloadParts) -> Result<Self, Problem> {
        let OtherPayloadParts { value } = parts;
        let value = Self { value };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `value` field.
    #[must_use]
    pub fn value(&self) -> u8 { self.value }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> OtherPayloadParts { OtherPayloadParts { value: self.value } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        let Self { .. } = self;
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// `Shared` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Shared {
    /// `first` carrying `Payload`.
    First(Payload),
    /// `second` carrying `Payload`.
    Second(Payload),
    /// `other` carrying `OtherPayload`.
    Other(OtherPayload),
    /// `empty` without a payload.
    Empty,
}

impl Shared {
    /// Checks the payload against the given limits.
    pub fn new(limits: &Limits, value: Self) -> Result<Self, Problem> {
        value.check(limits)?;
        Ok(value)
    }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        match self {
            Self::First(record) | Self::Second(record) => Payload::check(record, limits),
            Self::Other(record) => OtherPayload::check(record, limits),
            Self::Empty => Ok(()),
        }?;
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// Movable fields of `OneByteItems`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct OneByteItemsParts {
    /// The `items` field.
    pub items: List<Shared>,
}

/// `OneByteItems` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct OneByteItems {
    items: List<Shared>,
}

impl OneByteItems {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: OneByteItemsParts) -> Result<Self, Problem> {
        let OneByteItemsParts { items } = parts;
        let value = Self { items };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `items` field.
    #[must_use]
    pub fn items(&self) -> &List<Shared> { &self.items }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> OneByteItemsParts { OneByteItemsParts { items: self.items } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if limits.payload_data > CEILINGS.payload_data { return Err(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Bound }); }
        if limits.one_byte_items_items > CEILINGS.one_byte_items_items { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        if self.items.capacity() > limits.one_byte_items_items.min(CEILINGS.one_byte_items_items) { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Bound }); }
        for item_0 in self.items.as_slice() {
        item_0.check(limits)?;
        }
        Ok(())
    }
}

impl HostTool {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(4).expect("schema ceilings fit u32");
        let field_payload = &self.payload;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size = size.checked_add(u32::try_from(field_payload.len()).expect("field ceiling fits u32")).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_inspect = &self.inspect();
        writer.put(&[u8::from(*field_inspect)])?;
        let field_modify = &self.modify();
        writer.put(&[u8::from(*field_modify)])?;
        let field_shell = &self.shell();
        writer.put(&[u8::from(*field_shell)])?;
        let field_agents = &self.agents();
        writer.put(&[u8::from(*field_agents)])?;
        let field_max_tokens = &self.max_tokens;
        writer.put(&field_max_tokens.to_be_bytes())?;
        let field_payload = &self.payload;
        writer.put(&u32::try_from(field_payload.len()).expect("field ceiling fits u32").to_be_bytes())?;
        writer.put(field_payload.as_ref())?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::HostToolTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_inspect = match reader.u8().ok_or(Problem { path: Path::HostToolInspect, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolInspect, reason: skein_codec::Reason::Bool }) };
        let decoded_modify = match reader.u8().ok_or(Problem { path: Path::HostToolModify, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolModify, reason: skein_codec::Reason::Bool }) };
        let decoded_shell = match reader.u8().ok_or(Problem { path: Path::HostToolShell, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolShell, reason: skein_codec::Reason::Bool }) };
        let decoded_agents = match reader.u8().ok_or(Problem { path: Path::HostToolAgents, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolAgents, reason: skein_codec::Reason::Bool }) };
        let decoded_max_tokens = reader.u32().ok_or(Problem { path: Path::HostToolMaxTokens, reason: skein_codec::Reason::Short })?;
        let decoded_payload = { let length = match skein_codec::read_len(reader, limits.host_tool_payload.min(CEILINGS.host_tool_payload)) { Ok(length) => length, Err(reason) => return Err(Problem { path: Path::HostToolPayload, reason }), }; Box::from(reader.bytes(length).ok_or(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Short })?) };
        Self::new(limits, HostToolParts { skein_bools: [decoded_inspect, decoded_modify, decoded_shell, decoded_agents], max_tokens: decoded_max_tokens, payload: decoded_payload })
    }
}

impl Boundless {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_count = &self.count;
        writer.put(&field_count.to_be_bytes())?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::BoundlessTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_count = reader.u32().ok_or(Problem { path: Path::BoundlessCount, reason: skein_codec::Reason::Short })?;
        Self::new(limits, BoundlessParts { count: decoded_count })
    }
}

impl Payload {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        let field_data = &self.data;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size = size.checked_add(u32::try_from(field_data.len()).expect("field ceiling fits u32")).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_data = &self.data;
        writer.put(&u32::try_from(field_data.len()).expect("field ceiling fits u32").to_be_bytes())?;
        writer.put(field_data.as_ref())?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::PayloadTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_data = { let length = match skein_codec::read_len(reader, limits.payload_data.min(CEILINGS.payload_data)) { Ok(length) => length, Err(reason) => return Err(Problem { path: Path::PayloadData, reason }), }; Box::from(reader.bytes(length).ok_or(Problem { path: Path::PayloadData, reason: skein_codec::Reason::Short })?) };
        Self::new(limits, PayloadParts { data: decoded_data })
    }
}

impl OtherPayload {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_value = &self.value;
        writer.put(&[*field_value])?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::OtherPayloadTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_value = reader.u8().ok_or(Problem { path: Path::OtherPayloadValue, reason: skein_codec::Reason::Short })?;
        Self::new(limits, OtherPayloadParts { value: decoded_value })
    }
}

impl Shared {
    /// Measures this variant's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        match self {
            Self::First(record) | Self::Second(record) => 1_u32.checked_add(Payload::measure(record)).expect("schema ceilings fit u32"),
            Self::Other(record) => 1_u32.checked_add(OtherPayload::measure(record)).expect("schema ceilings fit u32"),
            Self::Empty => 1,
        }
    }

    /// Writes this variant's tag and payload.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        match self {
            Self::First(record) => { writer.put(&[0_u8])?; record.encode(writer)?; }
            Self::Second(record) => { writer.put(&[1_u8])?; record.encode(writer)?; }
            Self::Other(record) => { writer.put(&[2_u8])?; record.encode(writer)?; }
            Self::Empty => writer.put(&[3_u8])?,
        }
        Ok(())
    }

    /// Reads a whole variant and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::SharedTag, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let tag = reader.u8().ok_or(Problem { path: Path::SharedTag, reason: skein_codec::Reason::Short })?;
        let value = match tag {
            0 => Self::First(Payload::decode_from(limits, reader)?),
            1 => Self::Second(Payload::decode_from(limits, reader)?),
            2 => Self::Other(OtherPayload::decode_from(limits, reader)?),
            3 => Self::Empty,
            _ => return Err(Problem { path: Path::SharedTag, reason: skein_codec::Reason::Tag }),
        };
        Self::new(limits, value)
    }
}

impl OneByteItems {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        let field_items = &self.items;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        for item_0 in field_items.as_slice() {
        size = size.checked_add(item_0.measure()).expect("schema ceilings fit u32");
        }
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_items = &self.items;
        writer.put(&field_items.len().to_be_bytes())?;
        for item_0 in field_items.as_slice() {
        item_0.encode(writer)?;
        }
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::OneByteItemsTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_items = { let count = match skein_codec::read_count(reader, limits.one_byte_items_items.min(CEILINGS.one_byte_items_items)) { Ok(count) => count, Err(reason) => return Err(Problem { path: Path::OneByteItemsItems, reason }), }; if count > reader.remaining() { return Err(Problem { path: Path::OneByteItemsItems, reason: skein_codec::Reason::Short }); } let mut items_0 = List::with_capacity(count); for _index in 0_u32..count { let item = Shared::decode_from(limits, reader)?; items_0.push(item).expect("count within capacity"); } items_0 };
        Self::new(limits, OneByteItemsParts { items: decoded_items })
    }
}

fn limits_valid(limits: &Limits) -> bool {
    limits.host_tool_payload <= CEILINGS.host_tool_payload && limits.payload_data <= CEILINGS.payload_data && limits.one_byte_items_items <= CEILINGS.one_byte_items_items
}

impl HostTool {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(4_u64)?;
        size = size.checked_add(4_u64.checked_add(u64::from(limits.host_tool_payload))?)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(u64::from(limits.host_tool_payload))?;
        Some(heap)
    }
}

impl Boundless {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(4_u64)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        Some(heap)
    }
}

impl Payload {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(4_u64.checked_add(u64::from(limits.payload_data))?)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(u64::from(limits.payload_data))?;
        Some(heap)
    }
}

impl OtherPayload {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(1_u64)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        Some(heap)
    }
}

impl Shared {
    /// Maximum encoded bytes among variants.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut biggest = 0_u64;
        biggest = biggest.max(Payload::worst_case_bytes(limits)?);
        biggest = biggest.max(Payload::worst_case_bytes(limits)?);
        biggest = biggest.max(OtherPayload::worst_case_bytes(limits)?);
        1_u64.checked_add(biggest)
    }

    /// Maximum heap held by any decoded variant.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut biggest = 0_u64;
        biggest = biggest.max(Payload::worst_case_heap(limits)?);
        biggest = biggest.max(Payload::worst_case_heap(limits)?);
        biggest = biggest.max(OtherPayload::worst_case_heap(limits)?);
        Some(biggest)
    }
}

impl OneByteItems {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(4_u64.checked_add(u64::from(limits.one_byte_items_items).checked_mul(Shared::worst_case_bytes(limits)?)?)?)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(List::<Shared>::worst_case(limits.one_byte_items_items)?.checked_add(u64::from(limits.one_byte_items_items).checked_mul(Shared::worst_case_heap(limits)?)?)?)?;
        Some(heap)
    }
}

/// Maximum wire bytes among this family's top-level types.
#[must_use]
pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(HostTool::worst_case_bytes(limits)?);
    biggest = biggest.max(Boundless::worst_case_bytes(limits)?);
    biggest = biggest.max(Payload::worst_case_bytes(limits)?);
    biggest = biggest.max(OtherPayload::worst_case_bytes(limits)?);
    biggest = biggest.max(Shared::worst_case_bytes(limits)?);
    biggest = biggest.max(OneByteItems::worst_case_bytes(limits)?);
    Some(biggest)
}

/// Maximum heap held by one decoded top-level value.
#[must_use]
pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(HostTool::worst_case_heap(limits)?);
    biggest = biggest.max(Boundless::worst_case_heap(limits)?);
    biggest = biggest.max(Payload::worst_case_heap(limits)?);
    biggest = biggest.max(OtherPayload::worst_case_heap(limits)?);
    biggest = biggest.max(Shared::worst_case_heap(limits)?);
    biggest = biggest.max(OneByteItems::worst_case_heap(limits)?);
    Some(biggest)
}

#[cfg(test)]
mod golden_tests {
    use super::{CEILINGS, Path, HostTool, HostToolParts, Boundless, BoundlessParts, Payload, PayloadParts, OtherPayload, OtherPayloadParts, Shared, OneByteItems, OneByteItemsParts};
    use alloc::boxed::Box;

    #[test]
    fn record_host_tool_smallest() {
        let value = HostTool::new(&CEILINGS, HostToolParts { skein_bools: [false, false, false, false], max_tokens: 0_u32, payload: Box::from([].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_host_tool_full() {
        let value = HostTool::new(&CEILINGS, HostToolParts { skein_bools: [true, true, true, true], max_tokens: u32::MAX, payload: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[1, 1, 1, 1, 255, 255, 255, 255, 0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_boundless_smallest() {
        let value = Boundless::new(&CEILINGS, BoundlessParts { count: 0_u32 }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Boundless::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_boundless_full() {
        let value = Boundless::new(&CEILINGS, BoundlessParts { count: u32::MAX }).expect("golden within ceilings");
        let golden: &[u8] = &[255, 255, 255, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Boundless::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_payload_smallest() {
        let value = Payload::new(&CEILINGS, PayloadParts { data: Box::from([].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Payload::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_payload_full() {
        let value = Payload::new(&CEILINGS, PayloadParts { data: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Payload::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_other_payload_smallest() {
        let value = OtherPayload::new(&CEILINGS, OtherPayloadParts { value: 0_u8 }).expect("golden within ceilings");
        let golden: &[u8] = &[0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(OtherPayload::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_other_payload_full() {
        let value = OtherPayload::new(&CEILINGS, OtherPayloadParts { value: u8::MAX }).expect("golden within ceilings");
        let golden: &[u8] = &[255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(OtherPayload::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_first_smallest() {
        let value = Shared::First(Payload::new(&CEILINGS, PayloadParts { data: Box::from([].as_slice()) }).expect("golden within ceilings"));
        let golden: &[u8] = &[0, 0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_first_full() {
        let value = Shared::First(Payload::new(&CEILINGS, PayloadParts { data: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings"));
        let golden: &[u8] = &[0, 0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_second_smallest() {
        let value = Shared::Second(Payload::new(&CEILINGS, PayloadParts { data: Box::from([].as_slice()) }).expect("golden within ceilings"));
        let golden: &[u8] = &[1, 0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_second_full() {
        let value = Shared::Second(Payload::new(&CEILINGS, PayloadParts { data: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings"));
        let golden: &[u8] = &[1, 0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_other_smallest() {
        let value = Shared::Other(OtherPayload::new(&CEILINGS, OtherPayloadParts { value: 0_u8 }).expect("golden within ceilings"));
        let golden: &[u8] = &[2, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_other_full() {
        let value = Shared::Other(OtherPayload::new(&CEILINGS, OtherPayloadParts { value: u8::MAX }).expect("golden within ceilings"));
        let golden: &[u8] = &[2, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_empty_smallest() {
        let value = Shared::Empty;
        let golden: &[u8] = &[3];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn enum_shared_empty_full() {
        let value = Shared::Empty;
        let golden: &[u8] = &[3];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Shared::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_one_byte_items_smallest() {
        let value = OneByteItems::new(&CEILINGS, OneByteItemsParts { items: skein_lib::List::with_capacity(0) }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(OneByteItems::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_one_byte_items_full() {
        let value = OneByteItems::new(&CEILINGS, OneByteItemsParts { items: { let mut items = skein_lib::List::with_capacity(1); items.push(Shared::First(Payload::new(&CEILINGS, PayloadParts { data: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings"))).expect("one slot"); items } }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(OneByteItems::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn bound_host_tool_payload() {
        fn wire(count: u32, payload: bool) -> Box<[u8]> {
            let body = usize::try_from(count).expect("u32 fits usize").checked_mul(1).expect("schema ceiling");
            let header = 8_usize.checked_add(4).expect("header size");
            let total = if payload { let with_body = header.checked_add(body).expect("body size"); with_body.checked_add(0_usize).expect("wire size") } else { header };
            let mut writer = skein_lib::Writer::new(total);
            writer.put(&[0, 0, 0, 0, 0, 0, 0, 0]).expect("prefix room");
            writer.put(&count.to_be_bytes()).expect("length room");
            if payload {
                writer.put(&skein_lib::bytes::zeroed(body)).expect("body room");
                writer.put(&[]).expect("suffix room");
            }
            writer.finish()
        }
        HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(10_000, true))).expect("field at ceiling");
        let problem = HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(10_001, false))).expect_err("field past ceiling");
        assert_eq!((problem.path, problem.reason), (Path::HostToolPayload, skein_codec::Reason::Bound));
    }

    #[test]
    fn bound_payload_data() {
        fn wire(count: u32, payload: bool) -> Box<[u8]> {
            let body = usize::try_from(count).expect("u32 fits usize").checked_mul(1).expect("schema ceiling");
            let header = 0_usize.checked_add(4).expect("header size");
            let total = if payload { let with_body = header.checked_add(body).expect("body size"); with_body.checked_add(0_usize).expect("wire size") } else { header };
            let mut writer = skein_lib::Writer::new(total);
            writer.put(&[]).expect("prefix room");
            writer.put(&count.to_be_bytes()).expect("length room");
            if payload {
                writer.put(&skein_lib::bytes::zeroed(body)).expect("body room");
                writer.put(&[]).expect("suffix room");
            }
            writer.finish()
        }
        Payload::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(4, true))).expect("field at ceiling");
        let problem = Payload::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(5, false))).expect_err("field past ceiling");
        assert_eq!((problem.path, problem.reason), (Path::PayloadData, skein_codec::Reason::Bound));
    }

    #[test]
    fn bound_one_byte_items_items() {
        fn wire(count: u32, payload: bool) -> Box<[u8]> {
            let body = usize::try_from(count).expect("u32 fits usize").checked_mul(5).expect("schema ceiling");
            let header = 0_usize.checked_add(4).expect("header size");
            let total = if payload { let with_body = header.checked_add(body).expect("body size"); with_body.checked_add(0_usize).expect("wire size") } else { header };
            let mut writer = skein_lib::Writer::new(total);
            writer.put(&[]).expect("prefix room");
            writer.put(&count.to_be_bytes()).expect("length room");
            if payload {
                for _item in 0_u32..count { writer.put(&[0, 0, 0, 0, 0]).expect("item room"); }
                writer.put(&[]).expect("suffix room");
            }
            writer.finish()
        }
        OneByteItems::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(4, true))).expect("field at ceiling");
        let problem = OneByteItems::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(5, false))).expect_err("field past ceiling");
        assert_eq!((problem.path, problem.reason), (Path::OneByteItemsItems, skein_codec::Reason::Bound));
    }

}
