// Generated by skein-codegen from lint-fixture 1. Do not edit.

use alloc::boxed::Box;

/// The family's adjustable limits, each no larger than its ceiling.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Limits {
    pub host_tool_payload: u32,
}

/// The schema's maximum limits.
pub const CEILINGS: Limits = Limits {
    host_tool_payload: 10_000,
};

/// A field or tag that caused a codec problem.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Path {
    /// The `inspect` field of `HostTool`.
    HostToolInspect,
    /// The `modify` field of `HostTool`.
    HostToolModify,
    /// The `shell` field of `HostTool`.
    HostToolShell,
    /// The `agents` field of `HostTool`.
    HostToolAgents,
    /// The `max_tokens` field of `HostTool`.
    HostToolMaxTokens,
    /// The `payload` field of `HostTool`.
    HostToolPayload,
    /// Bytes after `HostTool`.
    HostToolTail,
    /// The `count` field of `Boundless`.
    BoundlessCount,
    /// Bytes after `Boundless`.
    BoundlessTail,
}

/// A decoding or bound failure at a schema path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Problem {
    pub path: Path,
    pub reason: skein_codec::Reason,
}

/// Movable fields of `HostTool`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct HostToolParts {
    /// Boolean fields in schema order.
    pub skein_bools: [bool; 4],
    /// The `max_tokens` field.
    pub max_tokens: u32,
    /// The `payload` field.
    pub payload: Box<[u8]>,
}

/// `HostTool` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct HostTool {
    skein_bools: [bool; 4],
    max_tokens: u32,
    payload: Box<[u8]>,
}

impl HostTool {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: HostToolParts) -> Result<Self, Problem> {
        let HostToolParts { skein_bools, max_tokens, payload } = parts;
        let value = Self { skein_bools, max_tokens, payload };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `inspect` field.
    #[must_use]
    pub fn inspect(&self) -> bool { { let [value, _, _, _] = self.skein_bools; value } }

    /// Reads the `modify` field.
    #[must_use]
    pub fn modify(&self) -> bool { { let [_, value, _, _] = self.skein_bools; value } }

    /// Reads the `shell` field.
    #[must_use]
    pub fn shell(&self) -> bool { { let [_, _, value, _] = self.skein_bools; value } }

    /// Reads the `agents` field.
    #[must_use]
    pub fn agents(&self) -> bool { { let [_, _, _, value] = self.skein_bools; value } }

    /// Reads the `max_tokens` field.
    #[must_use]
    pub fn max_tokens(&self) -> u32 { self.max_tokens }

    /// Reads the `payload` field.
    #[must_use]
    pub fn payload(&self) -> &[u8] { &self.payload }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> HostToolParts { HostToolParts { skein_bools: self.skein_bools, max_tokens: self.max_tokens, payload: self.payload } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        if self.payload.len() > usize::try_from(limits.host_tool_payload.min(CEILINGS.host_tool_payload)).expect("u32 fits usize") { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

/// Movable fields of `Boundless`.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct BoundlessParts {
    /// The `count` field.
    pub count: u32,
}

/// `Boundless` in this codec family.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Boundless {
    count: u32,
}

impl Boundless {
    /// Makes a value within the given limits.
    pub fn new(limits: &Limits, parts: BoundlessParts) -> Result<Self, Problem> {
        let BoundlessParts { count } = parts;
        let value = Self { count };
        value.check(limits)?;
        Ok(value)
    }

    /// Reads the `count` field.
    #[must_use]
    pub fn count(&self) -> u32 { self.count }

    /// Moves the fields out without copying.
    #[must_use]
    pub fn into_parts(self) -> BoundlessParts { BoundlessParts { count: self.count } }

    fn check(&self, limits: &Limits) -> Result<(), Problem> {
        let Self { .. } = self;
        if limits.host_tool_payload > CEILINGS.host_tool_payload { return Err(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Bound }); }
        Ok(())
    }
}

impl HostTool {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(1).expect("schema ceilings fit u32");
        size = size.checked_add(4).expect("schema ceilings fit u32");
        let field_payload = &self.payload;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size = size.checked_add(u32::try_from(field_payload.len()).expect("field ceiling fits u32")).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_inspect = &self.inspect();
        writer.put(&[u8::from(*field_inspect)])?;
        let field_modify = &self.modify();
        writer.put(&[u8::from(*field_modify)])?;
        let field_shell = &self.shell();
        writer.put(&[u8::from(*field_shell)])?;
        let field_agents = &self.agents();
        writer.put(&[u8::from(*field_agents)])?;
        let field_max_tokens = &self.max_tokens;
        writer.put(&field_max_tokens.to_be_bytes())?;
        let field_payload = &self.payload;
        writer.put(&u32::try_from(field_payload.len()).expect("field ceiling fits u32").to_be_bytes())?;
        writer.put(field_payload.as_ref())?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::HostToolTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_inspect = match reader.u8().ok_or(Problem { path: Path::HostToolInspect, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolInspect, reason: skein_codec::Reason::Bool }) };
        let decoded_modify = match reader.u8().ok_or(Problem { path: Path::HostToolModify, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolModify, reason: skein_codec::Reason::Bool }) };
        let decoded_shell = match reader.u8().ok_or(Problem { path: Path::HostToolShell, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolShell, reason: skein_codec::Reason::Bool }) };
        let decoded_agents = match reader.u8().ok_or(Problem { path: Path::HostToolAgents, reason: skein_codec::Reason::Short })? { 0 => false, 1 => true, _ => return Err(Problem { path: Path::HostToolAgents, reason: skein_codec::Reason::Bool }) };
        let decoded_max_tokens = reader.u32().ok_or(Problem { path: Path::HostToolMaxTokens, reason: skein_codec::Reason::Short })?;
        let decoded_payload = { let length = match skein_codec::read_len(reader, limits.host_tool_payload.min(CEILINGS.host_tool_payload)) { Ok(length) => length, Err(reason) => return Err(Problem { path: Path::HostToolPayload, reason }), }; Box::from(reader.bytes(length).ok_or(Problem { path: Path::HostToolPayload, reason: skein_codec::Reason::Short })?) };
        Self::new(limits, HostToolParts { skein_bools: [decoded_inspect, decoded_modify, decoded_shell, decoded_agents], max_tokens: decoded_max_tokens, payload: decoded_payload })
    }
}

impl Boundless {
    /// Measures this record's wire encoding.
    #[must_use]
    pub fn measure(&self) -> u32 {
        let mut size = 0_u32;
        size = size.checked_add(4).expect("schema ceilings fit u32");
        size
    }

    /// Writes into a writer with room for the measured bytes.
    pub fn encode(&self, writer: &mut skein_lib::Writer) -> Result<(), skein_lib::Overflow> {
        let field_count = &self.count;
        writer.put(&field_count.to_be_bytes())?;
        Ok(())
    }

    /// Reads a whole record and refuses trailing bytes.
    pub fn decode(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let value = Self::decode_from(limits, reader)?;
        if !reader.is_empty() { return Err(Problem { path: Path::BoundlessTail, reason: skein_codec::Reason::Trailing }); }
        Ok(value)
    }

    fn decode_from(limits: &Limits, reader: &mut skein_lib::Reader<'_>) -> Result<Self, Problem> {
        let decoded_count = reader.u32().ok_or(Problem { path: Path::BoundlessCount, reason: skein_codec::Reason::Short })?;
        Self::new(limits, BoundlessParts { count: decoded_count })
    }
}

fn limits_valid(limits: &Limits) -> bool {
    limits.host_tool_payload <= CEILINGS.host_tool_payload
}

impl HostTool {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(1_u64)?;
        size = size.checked_add(4_u64)?;
        size = size.checked_add(4_u64.checked_add(u64::from(limits.host_tool_payload))?)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(0_u64)?;
        heap = heap.checked_add(u64::from(limits.host_tool_payload))?;
        Some(heap)
    }
}

impl Boundless {
    /// Maximum encoded bytes under these limits.
    #[must_use]
    pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut size = 0_u64;
        size = size.checked_add(4_u64)?;
        Some(size)
    }

    /// Maximum heap held by one decoded value under these limits.
    #[must_use]
    pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
        if !limits_valid(limits) { return None; }
        let mut heap = 0_u64;
        heap = heap.checked_add(0_u64)?;
        Some(heap)
    }
}

/// Maximum wire bytes among this family's top-level types.
#[must_use]
pub fn worst_case_bytes(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(HostTool::worst_case_bytes(limits)?);
    biggest = biggest.max(Boundless::worst_case_bytes(limits)?);
    Some(biggest)
}

/// Maximum heap held by one decoded top-level value.
#[must_use]
pub fn worst_case_heap(limits: &Limits) -> Option<u64> {
    if !limits_valid(limits) { return None; }
    let mut biggest = 0_u64;
    biggest = biggest.max(HostTool::worst_case_heap(limits)?);
    biggest = biggest.max(Boundless::worst_case_heap(limits)?);
    Some(biggest)
}

#[cfg(test)]
mod golden_tests {
    use super::{CEILINGS, Path, HostTool, HostToolParts, Boundless, BoundlessParts};
    use alloc::boxed::Box;

    #[test]
    fn record_host_tool_smallest() {
        let value = HostTool::new(&CEILINGS, HostToolParts { skein_bools: [false, false, false, false], max_tokens: 0_u32, payload: Box::from([].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_host_tool_full() {
        let value = HostTool::new(&CEILINGS, HostToolParts { skein_bools: [true, true, true, true], max_tokens: u32::MAX, payload: Box::from([0_u8, 127_u8, 255_u8].as_slice()) }).expect("golden within ceilings");
        let golden: &[u8] = &[1, 1, 1, 1, 255, 255, 255, 255, 0, 0, 0, 3, 0, 127, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_boundless_smallest() {
        let value = Boundless::new(&CEILINGS, BoundlessParts { count: 0_u32 }).expect("golden within ceilings");
        let golden: &[u8] = &[0, 0, 0, 0];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Boundless::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn record_boundless_full() {
        let value = Boundless::new(&CEILINGS, BoundlessParts { count: u32::MAX }).expect("golden within ceilings");
        let golden: &[u8] = &[255, 255, 255, 255];
        let mut writer = skein_lib::Writer::new(usize::try_from(value.measure()).expect("size fits usize"));
        value.encode(&mut writer).expect("measured room");
        assert_eq!(writer.finish().as_ref(), golden);
        assert_eq!(Boundless::decode(&CEILINGS, &mut skein_lib::Reader::new(golden)), Ok(value));
    }

    #[test]
    fn bound_host_tool_payload() {
        fn wire(count: u32, payload: bool) -> Box<[u8]> {
            let body = usize::try_from(count).expect("u32 fits usize").checked_mul(1).expect("schema ceiling");
            let header = 8_usize.checked_add(4).expect("header size");
            let total = if payload { let with_body = header.checked_add(body).expect("body size"); with_body.checked_add(0_usize).expect("wire size") } else { header };
            let mut writer = skein_lib::Writer::new(total);
            writer.put(&[0, 0, 0, 0, 0, 0, 0, 0]).expect("prefix room");
            writer.put(&count.to_be_bytes()).expect("length room");
            if payload {
                writer.put(&skein_lib::bytes::zeroed(body)).expect("body room");
                writer.put(&[]).expect("suffix room");
            }
            writer.finish()
        }
        HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(10_000, true))).expect("field at ceiling");
        let problem = HostTool::decode(&CEILINGS, &mut skein_lib::Reader::new(&wire(10_001, false))).expect_err("field past ceiling");
        assert_eq!((problem.path, problem.reason), (Path::HostToolPayload, skein_codec::Reason::Bound));
    }

}
